/*
  Abbreviations taken from: https://biblia.apologetyka.com/help#shortcuts
  Numbers of chapters taken from: http://www.greatcommission.com/BibleBookChapters.htm
*/
const books = [
  //OLD TESTAMENT
  {abbrev: "gen", numberOfChapters: 50},
  {abbrev: "exo", numberOfChapters: 40},
  {abbrev: "lev", numberOfChapters: 27},
  {abbrev: "num", numberOfChapters: 36},
  {abbrev: "deu", numberOfChapters: 34},
  {abbrev: "jos", numberOfChapters: 24},
  {abbrev: "jdg", numberOfChapters: 21},
  {abbrev: "rut", numberOfChapters: 4},
  {abbrev: "1sa", numberOfChapters: 31},
  {abbrev: "2sa", numberOfChapters: 24},
  {abbrev: "1ki", numberOfChapters: 22},
  {abbrev: "2ki", numberOfChapters: 25},
  {abbrev: "1ch", numberOfChapters: 29},
  {abbrev: "2ch", numberOfChapters: 36},
  {abbrev: "ezr", numberOfChapters: 10},
  {abbrev: "neh", numberOfChapters: 13},
  {abbrev: "est", numberOfChapters: 10},
  {abbrev: "job", numberOfChapters: 42},
  {abbrev: "psa", numberOfChapters: 150},
  {abbrev: "pro", numberOfChapters: 31},
  {abbrev: "ecc", numberOfChapters: 12},
  {abbrev: "sol", numberOfChapters: 8},
  {abbrev: "isa", numberOfChapters: 66},
  {abbrev: "jer", numberOfChapters: 52},
  {abbrev: "lam", numberOfChapters: 5},
  {abbrev: "eze", numberOfChapters: 48},
  {abbrev: "dan", numberOfChapters: 12},
  {abbrev: "hos", numberOfChapters: 14},
  {abbrev: "joe", numberOfChapters: 3},
  {abbrev: "amo", numberOfChapters: 9},
  {abbrev: "oba", numberOfChapters: 1},
  {abbrev: "jon", numberOfChapters: 4},
  {abbrev: "mic", numberOfChapters: 7},
  {abbrev: "nah", numberOfChapters: 3},
  {abbrev: "hab", numberOfChapters: 3},
  {abbrev: "zep", numberOfChapters: 3},
  {abbrev: "hag", numberOfChapters: 2},
  {abbrev: "zec", numberOfChapters: 14},
  {abbrev: "mal", numberOfChapters: 4},
  //NEW TESTAMENT
  {abbrev: "mat", numberOfChapters: 28},
  {abbrev: "mar", numberOfChapters: 16},
  {abbrev: "luk", numberOfChapters: 24},
  {abbrev: "joh", numberOfChapters: 21},
  {abbrev: "act", numberOfChapters: 28},
  {abbrev: "rom", numberOfChapters: 16},
  {abbrev: "1co", numberOfChapters: 16},
  {abbrev: "2co", numberOfChapters: 13},
  {abbrev: "gal", numberOfChapters: 6},
  {abbrev: "eph", numberOfChapters: 6},
  {abbrev: "phi", numberOfChapters: 4},
  {abbrev: "col", numberOfChapters: 4},
  {abbrev: "1th", numberOfChapters: 5},
  {abbrev: "2th", numberOfChapters: 3},
  {abbrev: "1ti", numberOfChapters: 6},
  {abbrev: "2ti", numberOfChapters: 4},
  {abbrev: "tit", numberOfChapters: 3},
  {abbrev: "phm", numberOfChapters: 1},
  {abbrev: "heb", numberOfChapters: 13},
  {abbrev: "jam", numberOfChapters: 5},
  {abbrev: "1pe", numberOfChapters: 5},
  {abbrev: "2pe", numberOfChapters: 3},
  {abbrev: "1jo", numberOfChapters: 5},
  {abbrev: "2jo", numberOfChapters: 1},
  {abbrev: "3jo", numberOfChapters: 1},
  {abbrev: "jud", numberOfChapters: 1},
  {abbrev: "rev", numberOfChapters: 22},
]

// console.log(books.map(book => book.numberOfChapters).reduce((a,b) => a+b))

module.exports = books
